### ISSUE TITLE
Mark Assignment 4 for Laura Z

### ISSUE THREAD

**Issue by lzgles** [lzgles/week_04#1]
fa7fa33

@rharrington31

**Comment by rharrington31** [comment]
1. Good!
2. Good!
3. Good!
4. Good!
5. This doesn't quite work. Recall that we can directly `sum` logical vectors. You can simply use `~sum(.)` to get the answer.
6. Good!
7. Good!
8. This strategy works well. Another option could be to utilize the `%in%` operator. This would look like `Rec %in% c("Yes", "yes", "Y")`. This is normally easier than using `|`.
9. You wouldn't have learned it yet, but you'd likely want to utilize `pivot_longer` to graph this more effectively. You would want to create a variable column that contains "Length" and "Circumference" with a values column that contains their respective values. This works better than needing to layer on `geom_point` and `geom_smooth` for each variable you want to graph.
